CREATE TABLE claim(
    Id serial PRIMARY KEY ,
    UserId CHARACTER VARYING(30),
    Value CHARACTER VARYING(30)  NOT NULL,
    Key CHARACTER VARYING(30)  NOT NULL
);

ALTER TABLE claim ADD CONSTRAINT user_claim FOREIGN KEY (UserId) REFERENCES public.users (Login)  ON DELETE CASCADE;

